`include "/opt/tools/bsc/latest/lib/Verilog/ClockGen.v"
`include "/opt/tools/bsc/latest/lib/Verilog/ClockDiv.v"
`include "/opt/tools/bsc/latest/lib/Verilog/SyncFIFO.v"
`include "/opt/tools/bsc/latest/lib/Verilog/SyncReset0.v"
`include "/opt/tools/bsc/latest/lib/Verilog/SyncBit.v"